version: '3.2'
services:
  checkmk:
    build:
      context: .
      target: prod
    ports:
      - "8080:8080"
    networks:
      checkmk:
networks:
  checkmk:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.199.0/24
          gateway: 192.168.199.1
