site_name: Pure Storage Checkmk plugin
site_url: https://mkarg75.github.io/checkmk-purestorage/
repo_url: https://github.com/mkarg75/checkmk-purestorage/
repo_name: mkarg75/checkmk-purestorage
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - Installing:
      - 'installing/index.md'
  - FlashArray configuration:
      - 'flasharray/index.md'
  - FlashBlade configuration:
      - 'flashblade/index.md'
  - Enabling hardware/software inventory:
      - 'inventory/index.md'
  - Enabling alerts reporting:
      - 'alerts/index.md'
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mkarg75/checkmk-purestorage/
    - icon: fontawesome/solid/file-pdf
      link: "%pdf%"
  generator: false
plugins:
  - search
  - pdf-export:
      theme_handler_path: mkdocs-pdf-theme-handler.py
      media_type: print
      verbose: true
      combined: true
theme:
  name: material
  logo: pure.svg
  favicon: pure.svg
  font: false
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: white
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: black
      accent: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - navigation.footer
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - markdown.extensions.smarty:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true