#!/usr/bin/env python3

# This file is the entry point for the FlashArray special agent.

import sys

from purestorage_checkmk.flasharray import special_agent

sys.exit(special_agent.run(sys.stdin, sys.stdout))
