#!/usr/bin/env python3

# This file registers the FlashArray special agent. Since this file is loaded using eval and can't be interactively
# debugged, it serves as an indirection point to a module that can be debugged.

from cmk.base.config import special_agent_info
from purestorage_checkmk.flasharray.invoker import register

register(special_agent_info)
