import pprint
import unittest

from purestorage_checkmk.flasharray.common import FlashArraySpecialAgentResultsSection


class DecodeTest(unittest.TestCase):
    def test_decode(self):
        data = "eyJoYXJkd2FyZSI6IHsic2VydmljZXMiOiB7IkNUMC5FVEgzIjogeyJzdGF0ZSI6IDAsICJzdW1tYXJ5IjogIm9rIiwgImRldGFpbHMiOiAiZXRoIGRldGFpbHMsIHNwZWVkLCBtYWMsIGV0Yy4iLCAibm90aWNlIjogbnVsbH0sICJDVDAuRVRINCI6IHsic3RhdGUiOiAwLCAic3VtbWFyeSI6ICJvayIsICJkZXRhaWxzIjogImV0aCBkZXRhaWxzLCBzcGVlZCwgbWFjLCBldGMuIiwgIm5vdGljZSI6IG51bGx9LCAiQ1QxLkRDQTUiOiB7InN0YXRlIjogMCwgInN1bW1hcnkiOiAib2siLCAiZGV0YWlscyI6IG51bGwsICJub3RpY2UiOiBudWxsfSwgIkNUMS5EQ0E2IjogeyJzdGF0ZSI6IDAsICJzdW1tYXJ5IjogIm9rIiwgImRldGFpbHMiOiBudWxsLCAibm90aWNlIjogbnVsbH19LCAibWV0cmljcyI6IHt9fSwgImNlcnRpZmljYXRlcyI6IHsic2VydmljZXMiOiB7IkNlcnRpZmljYXRlMSI6IHsic3RhdGUiOiAwLCAic3VtbWFyeSI6IDE5ODMyNzc5MDYuMCwgImRldGFpbHMiOiAic2VsZi1zaWduZWQiLCAibm90aWNlIjogbnVsbH19LCAibWV0cmljcyI6IHsiQ2VydGlmaWNhdGUxIjogeyJ2YWx1ZSI6IDM0NDQuMTIyNTQ3Njg3NTE4NCwgImxldmVscyI6IFs5MCwgMzBdLCAiYm91bmRhcmllcyI6IFtudWxsLCBudWxsXX19fSwgImRyaXZlcyI6IHsic2VydmljZXMiOiB7IkNIMC5CQVkxIjogeyJzdGF0ZSI6IDAsICJzdW1tYXJ5IjogImhlYWx0aHkiLCAiZGV0YWlscyI6IG51bGwsICJub3RpY2UiOiBudWxsfX0sICJtZXRyaWNzIjoge319LCAiYXJyYXkiOiB7InNlcnZpY2VzIjogeyJBcnJheSAxIjogeyJzdGF0ZSI6IDAsICJzdW1tYXJ5IjogbnVsbCwgImRldGFpbHMiOiAiNzAuMCIsICJub3RpY2UiOiBudWxsfX0sICJtZXRyaWNzIjogeyJBcnJheSAxIjogeyJ2YWx1ZSI6IDcwLjAsICJsZXZlbHMiOiBbODAuMCwgOTAuMF0sICJib3VuZGFyaWVzIjogWzAsIDEwMF19fX0sICJjb250cm9sbGVycyI6IHsic2VydmljZXMiOiB7IkNUMSI6IHsic3RhdGUiOiAwLCAic3VtbWFyeSI6ICJyZWFkeSIsICJkZXRhaWxzIjogInNlY29uZGFyeSIsICJub3RpY2UiOiBudWxsfSwgIkNUMiI6IHsic3RhdGUiOiAwLCAic3VtbWFyeSI6ICJyZWFkeSIsICJkZXRhaWxzIjogInByaW1hcnkiLCAibm90aWNlIjogbnVsbH19LCAibWV0cmljcyI6IHt9fX0="
        decoded = FlashArraySpecialAgentResultsSection.from_section(data)
        pprint.pprint(decoded)
